#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_full.sv --exe f1_full_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_full.mk Vf1_full

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_full
echo "\nSimulation completed"

